version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    links:
    - influxdb
    depends_on:
      - influxdb
    environment:
      DB_HOSTNAME: influxdb
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - $PWD:/var/lib/influxdb
