version: '3'
services:
  web:
    build: ./src/
    # image: 'blairvee/rainyspring'
    ports:
      - "8080:8080"
    links:
      - influxdb
    depends_on:
      - influxdb
    environment:
      DB_HOSTNAME: localhost
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - $PWD:/var/lib/influxdb
